
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: prod
  name: app-cdn
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: prod
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"80":"app-cdn"}}'
  labels:
    release: stable
spec:
  selector:
    app: web
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: prod
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    release: stable
spec:
  selector:
    app: api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: web-service-cannary
  namespace: prod
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    release: cannary
spec:
  selector:
    app: web-cannary
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-service-cannary
  namespace: prod
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    release: cannary
spec:
  selector:
    app: api-cannary
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
