kind: Namespace
apiVersion: v1
metadata:
  name: kube-monitoring

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-prom
  namespace: kube-monitoring
spec:
  type: NodePort
  selector:
    pod: prom-pod
  ports:
  - port: 9090
    protocol: TCP
    name: prom-port

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: kube-monitoring
  labels:
    name: prompvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-prom
  namespace: kube-monitoring
spec:
  selector:
    matchLabels:
      pod: prom-pod
  replicas: 1
  template:
    metadata:
      labels:
        pod: prom-pod
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: prom-vol
            mountPath: /data/
      volumes:
      - name: prom-vol
        persistentVolumeClaim:
          claimName: prometheus-pvc
