# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: kube-state-metrics
#     k8s-app: kube-state-metrics
#   annotations:
#     alpha.monitoring.coreos.com/non-namespaced: "true"
#   name: kube-state-metrics
# spec:
#   ports:
#   - name: http-metrics
#     port: 8080
#     targetPort: metrics
#     protocol: TCP
#   selector:
#     app: kube-state-metrics
#
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: k8s-apps-http
#   labels:
#     release: stable
# spec:
#   jobLabel: k8s-app
#   selector:
#     matchExpressions:
#     - {key: release, operator: Exists}
#   namespaceSelector:
#     matchNames:
#     - kube-system
#     - monitoring
#     - prod
#   endpoints:
#   - port: http-metrics
#     interval: 15s

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-service-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  labels:
    app: web-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: web-service # target gitlab service
  endpoints:
  - port: metrics
    interval: 15s


apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-service
spec:
  selector:
    matchLabels:
      app: web-service
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web
    interval: 30s
